### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by slavakurilyak** [chec/headlesscommerce.org#108]
Running `$ yarn dev` gives the following error:

```
yarn run v1.22.10
$ next
ready - started server on http://localhost:3000
info  - Using external babel configuration from /Users/skurilyak/dev/testing/chec/headlesscommerce.org/.babelrc
event - compiled successfully
event - build page: /
wait  - compiling...
event - build page: /next/dist/pages/_error
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1305:9)
    at /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1407:9)
    at fetch (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at GraphQLClient.<anonymous> (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:159:46)
    at step (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:44:53)
    at /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:34:12)
    at GraphQLClient.request (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:151:16)
    at getPageBySlug (webpack-internal:///./lib/queries.ts:72:102)
    at getStaticProps (webpack-internal:///./pages/index.tsx:40:79)
    at renderToHTML (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/next/dist/next-server/server/render.js:28:115)
    at runMicrotasks (<anonymous>)
event - compiled successfully
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1305:9)
    at /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1407:9)
    at fetch (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at GraphQLClient.<anonymous> (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:159:46)
    at step (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:44:53)
    at /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:34:12)
    at GraphQLClient.request (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:151:16)
    at getPageBySlug (webpack-internal:///./lib/queries.ts:72:102)
    at getStaticProps (webpack-internal:///./pages/index.tsx:40:79)
    at renderToHTML (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/next/dist/next-server/server/render.js:28:115)
    at async /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/next/dist/next-server/server/next-server.js:99:97
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1305:9)
    at /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1407:9)
    at fetch (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at GraphQLClient.<anonymous> (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:159:46)
    at step (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:44:53)
    at /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:34:12)
    at GraphQLClient.request (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:151:16)
    at getPageBySlug (webpack-internal:///./lib/queries.ts:72:102)
    at getStaticProps (webpack-internal:///./pages/index.tsx:40:79)
    at renderToHTML (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/next/dist/next-server/server/render.js:28:115)
    at async /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/next/dist/next-server/server/next-server.js:99:97
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1305:9)
    at /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/node-fetch/lib/index.js:1407:9)
    at fetch (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at GraphQLClient.<anonymous> (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:159:46)
    at step (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:44:53)
    at /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:34:12)
    at GraphQLClient.request (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/graphql-request/dist/index.js:151:16)
    at getPageBySlug (webpack-internal:///./lib/queries.ts:72:102)
    at getStaticProps (webpack-internal:///./pages/index.tsx:40:79)
    at renderToHTML (/Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/next/dist/next-server/server/render.js:28:115)
    at async /Users/skurilyak/dev/testing/chec/headlesscommerce.org/node_modules/next/dist/next-server/server/next-server.js:99:97
```

![image](https://user-images.githubusercontent.com/6625584/103112700-f7bee700-460b-11eb-80b5-89f1b625ea82.png)

**Comment by slavakurilyak** [comment]
I was able to bypass this error by deploying to Netlify

**Comment by notrab** [comment]
@slavakurilyak you'll need to specify the ENV for the graphcms endpoint in `.env` if running locally - this is why the error is thrown. 

You should be able to see the updated `.env.sample` with the default values to get this going locally :)
